services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
  api:
    build: .
    command: npm run start
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - mongo

volumes:
  mongo-data:
    driver: local
